# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apteka' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  pod 'Alamofire'

end
